#!/bin/bash

sudo pacman -S libxinerama libxft xterm feh xdg-utils adobe-source-han-sans-jp-fonts

sudo make install clean -C ./st
sudo make install clean -C ./dwm
sudo make install clean -C ./dmenu
sudo make install clean -C ./slstatus

# X11
if ! [ -L "$XDG_CONFIG_HOME/X11" ];
then
  ln -s "$PWD/X11" $XDG_CONFIG_HOME
else
  echo "X11 symlink already exists"
fi
